# Generated by Django 3.2 on 2021-05-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0002_alter_vegetable_veg_cal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dairy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dairy_name', models.CharField(max_length=30)),
                ('dairy_cal', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish_name', models.CharField(max_length=30)),
                ('fish_cal', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Fruits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fruit_name', models.CharField(max_length=30)),
                ('fruit_cal', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Grain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grain_name', models.CharField(max_length=30)),
                ('grain_cal', models.FloatField()),
            ],
        ),
    ]
