# Generated by Django 3.2 on 2021-05-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0004_rename_fruits_fruit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meat_name', models.CharField(max_length=30)),
                ('meat_cal', models.FloatField()),
            ],
        ),
    ]
